"""Task Table change

Revision ID: e888b4ecac92
Revises: fd62721400ab
Create Date: 2026-02-24 15:36:42.493843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e888b4ecac92'
down_revision: Union[str, Sequence[str], None] = 'fd62721400ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'team_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('tasks_assignee_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_created_by_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_team_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_team_id_fkey'), 'tasks', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('tasks_created_by_id_fkey'), 'tasks', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('tasks_assignee_id_fkey'), 'tasks', 'users', ['assignee_id'], ['id'])
    op.alter_column('tasks', 'team_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
